CREATE TABLE IF NOT EXISTS qualit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    nicho TEXT NOT NULL,
    situacao TEXT NOT NULL,
    data DATE NOT NULL,
    hora TIME NOT NULL,
    canal TEXT NOT NULL,
    observacoes TEXT,
    status TEXT NOT NULL
);
INSERT INTO qualit VALUES ('3','JENIFER ANISTON','LOJA','ATENDIMENTO','2025-01-28','09:15','CHAT','PRECISA DE MAIS INFORMAçõES','OUTROS');
INSERT INTO qualit VALUES ('4','EMPRESA D','LOJA','ATENDIMENTO','2025-01-27','16:45','CHAT','SOLICITOU PROPOSTA','OUTROS');
INSERT INTO qualit VALUES ('5','EMPRESA E','LOJA','ATENDIMENTO','2025-01-26','11:00','CHAT','SEM INTERESSE NO MOMENTO','OUTROS');
INSERT INTO qualit VALUES ('6','EMPRESA F','LOJA','ATENDIMENTO','2025-01-25','13:20','CHAT','AGUARDANDO DOCUMENTAçãO','OUTROS');
INSERT INTO qualit VALUES ('7','EMPRESA G','SUPERMERCADO','ATENDIMENTO','2025-01-24','15:30','CHAT','CLIENTE RETORNOU CONTATO','OUTROS');
INSERT INTO qualit VALUES ('10','SONHAGRO','FARMÁCIA','ATENDIMENTO','2025-01-21','12:00','VOZ','SEM ORçAMENTO DISPONíVEL','OUTROS');
INSERT INTO qualit VALUES ('11','EMPRESA TESTE','LOJA','ATENDIMENTO','2025-01-30','10:00','CHAT','CLIENTE INTERESSADO','OUTROS');
INSERT INTO qualit VALUES ('13','NOVOS DADOS','FARMÁCIA','PROSPECÇÃO','2025-01-31','20:11','VOZ','MAIS UM TESTE','CHAMADA NÃO ATENDIDA');
INSERT INTO qualit VALUES ('16','SONHAGRO','SUPERMERCADO','PROSPECÇÃO','2025-02-01','00:00','VOZ','CLIENTE INTERESSADO','CAIXA POSTAL');
INSERT INTO qualit VALUES ('21','ROMARIO ME ALVES','LOJA','PROSPECÇÃO','2025-02-02','14:49','VOZ','NOVO TESTE','CHAMADA NÃO ATENDIDA');
INSERT INTO qualit VALUES ('22',' QUALIT','FARMÁCIA','ATENDIMENTO','2025-02-02','15:00','VOZ','TESTES','CHAMADA NÃO ATENDIDA');
INSERT INTO qualit VALUES ('24','LUCAS','FARMÁCIA','PROSPECÇÃO','2025-02-03','08:50','CHAT','SSSSZ','CHAMADA NÃO ATENDIDA');
INSERT INTO qualit VALUES ('26','DIEGO','FARMÁCIA','PROSPECÇÃO','2025-02-03','09:14','CHAT','APENAS TESTE','CONTATO INCORRETO');
INSERT INTO qualit VALUES ('27','BRUNO COSTA','LOJA','ATENDIMENTO','2025-02-03','09:17','CHAT','TESTE BRUNO','CAIXA POSTAL');
INSERT INTO qualit VALUES ('28','TESTE COM DATA','FARMÁCIA','ATENDIMENTO','2025-02-03','09:53','CHAT','OBSERVAÇÕES NOVAS','CAIXA POSTAL');